version: '1'

services:
  app:
    image: test-app:1.0
    ports:
      - "3000:3000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: hellothere
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    
volumes:
  db_data:
    driver: local
    