services:
  app:
    build:
      context: ./SmartRide
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      POSTGRES_DB: mydb
      POSTGRES_USER: hellothere
      POSTGRES_PASSWORD: 123456
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    command: sh -c "wget -O wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh && chmod +x wait-for-it.sh && ./wait-for-it.sh db:5432 -t 60 -- npm run start:prod"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hellothere -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: hellothere
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hellothere -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
